# Generated by Django 3.1.1 on 2020-09-01 22:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_auto_20200901_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAvailabilityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('day', models.DateField(help_text='Fecha disponibilidad', verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Seleccione planificacion', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_plan', to='main.planmodel', verbose_name='Planificacion')),
                ('teachers', models.ForeignKey(help_text='Seleccione profesor', on_delete=django.db.models.deletion.CASCADE, related_name='availability_teacher', to='main.teachermodel', verbose_name='Profesor')),
                ('term', models.ForeignKey(help_text='Periodo', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_term', to='main.termmodel', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Disponibilidad horaria',
                'verbose_name_plural': 'Disponibilidad horaria',
                'db_table': 'disponibilidad_horaria',
            },
        ),
    ]
