# Generated by Django 3.1.1 on 2020-09-03 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_timeavailabilitymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meshmodel',
            name='subjects',
        ),
        migrations.RemoveField(
            model_name='subjectmeshmodel',
            name='mesh',
        ),
        migrations.AddField(
            model_name='meshmodel',
            name='subject_mesh',
            field=models.ForeignKey(blank=True, help_text='Nivel', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='levels', to='main.subjectmeshmodel', verbose_name='Materia Malla'),
        ),
        migrations.AddField(
            model_name='subjectmeshmodel',
            name='level',
            field=models.IntegerField(default=1, help_text='Nivel carrera.', verbose_name='Nivel'),
        ),
    ]
