# Generated by Django 3.1.1 on 2020-09-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200902_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='skill',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Calificacion, destreza profesor [1-10]', verbose_name='Habilidad'),
        ),
        migrations.AlterField(
            model_name='classroommodel',
            name='affinity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, verbose_name='Afinidad'),
        ),
    ]
