# Generated by Django 3.1.1 on 2020-09-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200903_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='state',
            field=models.BooleanField(default=False, help_text='Estado de planificación.', verbose_name='Estado'),
        ),
    ]
