# Generated by Django 3.1.1 on 2020-09-05 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_planmodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='planmodel',
            name='date_emi',
            field=models.DateField(null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='planmodel',
            name='version',
            field=models.CharField(blank=True, default='', help_text='Version de la planificacion', max_length=20, verbose_name='Version'),
        ),
        migrations.CreateModel(
            name='LineItemScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('availability', models.ForeignKey(help_text='Disponibilidad horaria', on_delete=django.db.models.deletion.CASCADE, to='main.timeavailabilitymodel', verbose_name='Disponibilidad')),
                ('classroom', models.ForeignKey(help_text='Seleccionar el aula', on_delete=django.db.models.deletion.CASCADE, to='main.classroommodel', verbose_name='Clase')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.planmodel', verbose_name='Planificacion')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subjectmodel', verbose_name='Materia')),
                ('teacher', models.ForeignKey(help_text='Seleccione profesor(a)', on_delete=django.db.models.deletion.CASCADE, to='main.teachermodel', verbose_name='Profesor')),
            ],
            options={
                'verbose_name': 'Item planificacion',
                'verbose_name_plural': 'Items de planificacion',
                'db_table': 'planificacion_item',
            },
        ),
    ]
