# Generated by Django 3.1.1 on 2020-09-05 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200905_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeavailabilitymodel',
            name='plan',
        ),
    ]
