# Generated by Django 3.1.1 on 2020-09-07 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0012_auto_20200906_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineitemschedulemodel',
            name='availability',
            field=models.ForeignKey(help_text='Disponibilidad horaria', limit_choices_to={'status': True}, on_delete=django.db.models.deletion.CASCADE, to='main.timeavailabilitymodel', verbose_name='Disponibilidad'),
        ),
        migrations.AlterField(
            model_name='parallelmodel',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_parallels', to='main.planmodel', verbose_name='Planificación'),
        ),
        migrations.AlterField(
            model_name='parallelmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_parallels', to='main.teachermodel', verbose_name='Profesor'),
        ),
        migrations.AlterField(
            model_name='timeavailabilitymodel',
            name='num_end_day',
            field=models.CharField(blank=True, choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado'), ('7', 'Domingo')], help_text='Segundo día. Ej: Jueves.', max_length=5, null=True, verbose_name='Día 2'),
        ),
        migrations.CreateModel(
            name='BasicParallelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('code', models.CharField(help_text='B.', max_length=50, verbose_name='Alias')),
                ('description', models.TextField(default='', help_text='Referencia sobre el paralelo.', verbose_name='Descripción')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Base paralelo',
                'verbose_name_plural': 'Base paralelos',
                'db_table': 'base_paralelo',
            },
        ),
    ]
