# Generated by Django 3.1.1 on 2020-09-07 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_timeavailabilitymodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemschedulemodel',
            name='parallel',
            field=models.ForeignKey(blank=True, help_text='Seleccione paralelo', limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.parallelmodel', verbose_name='Paralelo'),
        ),
    ]
