# Generated by Django 3.1.1 on 2020-09-07 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_lineitemschedulemodel_parallel'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachermodel',
            name='afinity',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Afinidad del profesor [1-10]', verbose_name='Afinidad'),
        ),
    ]
