# Generated by Django 3.1.1 on 2020-09-07 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_careermodel_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachermodel',
            old_name='afinity',
            new_name='affinity',
        ),
    ]
