# Generated by Django 3.1.1 on 2020-09-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200907_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='parallelmodel',
            name='name',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ej: 1, 2, 3, etc.', verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='timeavailabilitymodel',
            name='num_end_day',
            field=models.CharField(blank=True, choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], help_text='Segundo día. Ej: Jueves.', max_length=5, null=True, verbose_name='Día 2'),
        ),
        migrations.AlterField(
            model_name='timeavailabilitymodel',
            name='num_start_day',
            field=models.CharField(choices=[('1', 'Lunes'), ('2', 'Martes'), ('3', 'Miércoles'), ('4', 'Jueves'), ('5', 'Viernes'), ('6', 'Sábado')], default='1', help_text='Día inicial. Ej: Lunes.', max_length=5, verbose_name='Día 1'),
        ),
    ]
