# Generated by Django 3.1.1 on 2020-09-08 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200907_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineitemschedulemodel',
            name='end_day',
            field=models.CharField(blank=True, default='', help_text='Día para la planificacion', max_length=120, null=True, verbose_name='Día 2'),
        ),
        migrations.AddField(
            model_name='lineitemschedulemodel',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Hora fin', null=True, verbose_name='Hora fin'),
        ),
        migrations.AddField(
            model_name='lineitemschedulemodel',
            name='start_day',
            field=models.CharField(blank=True, default='', help_text='Día para la planificacion', max_length=120, null=True, verbose_name='Día 1'),
        ),
        migrations.AddField(
            model_name='lineitemschedulemodel',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Hora inicio', null=True, verbose_name='Hora inicio'),
        ),
        migrations.AlterField(
            model_name='lineitemschedulemodel',
            name='availability',
            field=models.ForeignKey(blank=True, help_text='Disponibilidad horaria', limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.timeavailabilitymodel', verbose_name='Disponibilidad'),
        ),
    ]
