# Generated by Django 3.1 on 2020-08-30 03:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_userforeignkey.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilVersionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('academic_period', models.CharField(blank=True, default='', help_text='Periodo académico', max_length=150, null=True, verbose_name='Periodo academico')),
                ('generation_date', models.DateField(blank=True, help_text='Fecha de generación', null=True, verbose_name='Fecha generación')),
                ('version', models.CharField(help_text='Version de archivo', max_length=150, verbose_name='Version')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(help_text='Planificacion', on_delete=django.db.models.deletion.CASCADE, to='main.planmodel', verbose_name='Planificacion')),
            ],
            options={
                'verbose_name': 'Archivo version',
                'verbose_name_plural': 'Archivos version',
                'db_table': 'archivos_version',
            },
        ),
        migrations.CreateModel(
            name='IbmScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('day_week', models.PositiveSmallIntegerField(verbose_name='Día semana')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora Fin')),
                ('assigned_teacher', models.CharField(max_length=150, verbose_name='Profesor asignado')),
                ('assigned_classroom', models.CharField(max_length=150, verbose_name='Aula asignada')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.filversionmodel', verbose_name='Archivo version')),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'IBM Horario',
                'verbose_name_plural': 'IBM Horarios',
                'db_table': 'horario_ibm',
            },
        ),
        migrations.CreateModel(
            name='FilVersionDetailModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on which the object was created.', verbose_name='created_at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on which the object was last modified.', verbose_name='modified_at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted_at')),
                ('status', models.BooleanField(default=True, help_text='Status the object has currently', verbose_name='status')),
                ('name_file', models.CharField(max_length=100, verbose_name='Nombre Archivo')),
                ('type_file', models.CharField(default='', max_length=150, verbose_name='Tipo archivo')),
                ('generate_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Archivo generado')),
                ('creator', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('file_version', models.ForeignKey(help_text='Archivos de version.', on_delete=django.db.models.deletion.CASCADE, to='files.filversionmodel', verbose_name='Archivo version')),
                ('modifier', django_userforeignkey.models.fields.UserForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo version detalle',
                'verbose_name_plural': 'Archivos version detalles',
                'db_table': 'archivos_version_detalle',
            },
        ),
    ]
