# Generated by Django 3.1.1 on 2020-09-03 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filversionmodel',
            options={'verbose_name': 'Archivo versión', 'verbose_name_plural': 'Archivos versión'},
        ),
    ]
